dist: xenial

language: minimal

stages:
  - "unit tests"
  - "end-to-end tests"
  - "build image"
  - "release"

# Define yaml anchor to be reused across testing matrix
_end_to_end_script: &end_to_end_script
  if: (type = pull_request) AND (head_branch != master) AND (head_branch !~ /^v[0-9]+\.[0-9]+$/)
  script:
    - git clone https://github.com/iter8-tools/iter8-controller.git
    - iter8-controller/test/e2e/install-minikube.sh
    - iter8-controller/test/e2e/sanity-check.sh
    - iter8-controller/test/e2e/install-istio.sh
    - test/install-iter8.sh
    - test/install-iter8-trend.sh
    - test/e2e-test.sh

jobs:
  include:
    - stage: "unit tests"
      language: python
      python:
        - "3.7"
      if: (type = pull_request) AND (head_branch != master) AND (head_branch !~ /^v[0-9]+\.[0-9]+$/)
      install:
        - pip install -r requirements.txt
      script:
        - make test
    - stage: "end-to-end tests"
      env: KUBE_VERSION=v1.15.10 ISTIO_VERSION=1.4.3
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.15.10 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.16.0 ISTIO_VERSION=1.4.3
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.16.0 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - stage: "build image"
      if: (type = push) AND (branch = master OR branch =~ /^v[0-9]+\.[0-9]+/)
      script:
        - test/build-image.sh
    - stage: "release"
      script: skip
      if: (type = push) AND (branch =~ /^v[0-9]+\.[0-9]+/)
      before_deploy:
        - make ver=${TRAVIS_BRANCH} changelog > release.note
      deploy:
        provider: releases
        api_key: ${GITHUB_TOKEN}
        file: install/kubernetes/iter8-trend.yaml
        release_notes_file: release.note
        name: ${TRAVIS_BRANCH}
        draft: true
        skip_cleanup: true
        on:
          tags: true
